### ISSUE TITLE
error on malformed frontmatter

### ISSUE THREAD

**Issue by Dorianux** [mfarragher/obsidiantools#18]
in case of a malformed frontmatter in a document an exception is raised and not handled.

- error can be handled in https://github.com/mfarragher/obsidiantools/blob/ddd78669ef27346fdb4b13cdc956a6f8c00e98f4/obsidiantools/md_utils.py#L259
- adding the following solves the problem (allthough the specific error should be named)

```python
except:
    print("problem with file ", filepath)
```

**Comment by Dorianux** [comment]
sorry ... better is ...

```python
except:
    print("problem with file ", filepath)
    return {}, file_string
```

**Comment by louis030195** [comment]
Yeah. My front matter are messy due to having many integrations such as readwise.io which insert all my books, podcasts, audiobook notes, etc.

Workaround for broken frontmatter:
```py
        except:
            return {}, file_string
```

**Comment by louis030195** [comment]
```
Traceback (most recent call last):
  File "semantic/semantic_search_api.py", line 42, in <module>
    vault = otools.Vault(wkd).connect().gather()
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/obsidiantools/api.py", line 228, in connect
    wiki_link_map = self._get_wikilinks_index()
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/obsidiantools/api.py", line 508, in _get_wikilinks_index
    return {k: get_wikilinks(self._dirpath / v)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/obsidiantools/api.py", line 508, in <dictcomp>
    return {k: get_wikilinks(self._dirpath / v)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/obsidiantools/md_utils.py", line 106, in get_wikilinks
    src_txt = _get_source_text_from_md_file(filepath, remove_code=True)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/obsidiantools/md_utils.py", line 288, in _get_source_text_from_md_file
    html = _get_html_from_md_file(
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/obsidiantools/md_utils.py", line 268, in _get_html_from_md_file
    _, content = _get_md_front_matter_and_content(
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/obsidiantools/md_utils.py", line 249, in _get_md_front_matter_and_content
    return frontmatter.parse(file_string)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/frontmatter/__init__.py", line 82, in parse
    fm = handler.load(fm)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/frontmatter/default_handlers.py", line 238, in load
    return yaml.load(fm, **kwargs)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/louisbeaumont/Documents/brain/.obsidian/plugins/obsidian-ava/env/lib/python3.8/site-packages/yaml/parser.py", line 483, in parse_flow_sequence_entry
    raise ParserError("while parsing a flow sequence", self.marks[-1],
yaml.parser.ParserError: while parsing a flow sequence
  in "<unicode string>", line 3, column 10:
    aliases: [researchgate.net,(PDF) the Capa ... 
             ^
expected ',' or ']', but got '?'
  in "<unicode string>", line 3, column 98:
     ...  There Any Limit to Human Memory?]
```

**Comment by mfarragher** [comment]
I've updated the error handling - changes effective in [this version of `dev` branch](https://github.com/mfarragher/obsidiantools/tree/67e75bcfd197a056e2340f70a0de06a94b9dc739) (commit https://github.com/mfarragher/obsidiantools/commit/67e75bcfd197a056e2340f70a0de06a94b9dc739 ).

Example of a print statement for `ParserError`:
![error-print](https://user-images.githubusercontent.com/33595938/205447324-f5dbb550-dbc3-4efa-a3ff-935557732a42.png)
(there would be multiple print statements come up, because of the multiple file reads right now, which would be something to address as part of #16 )
